### ISSUE TITLE
Loops

### ISSUE THREAD

**Issue by jescalan** [posthtml/posthtml-exp#2]
So I know you have the [each helper](https://github.com/posthtml/posthtml-exp#each-) already, but I'm curious if there's anything built in here (or if there's another posthtml plugin that has it) to handle slightly more complex looping. For example:

```js
locals: {
  people: [
    { name: 'Doge', location: 'New York' },
    { name: 'Cate', location: 'California' }
  ]
}
```

Let's say I want to loop over this data and produce something like this:

```html
<ul>
  <li><strong>Doge</strong> lives in <strong>New York</strong></li>
  <li><strong>Cate</strong> lives in <strong>California</strong></li>
</ul>
```

Correct me if I'm wrong but there's no way to do this right now?

**Comment by michael-ciniawsky** [comment]
yes you're right, i'm working on a bigger update for the module, it has it's flaws and there needs to be a solution for block-level assignment, i'm trying to get a more generic approach where someone can 'register'  there own helpers, but rarely find spare time at the moment.
